language: android

jdk: oraclejdk8

env:
  global:
    - MALLOC_ARENA_MAX=2
    - ADB_INSTALL_TIMEOUT=10

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - android-sdk-license-5be876d5
    - android-sdk-license-c81a61d9

install:
  - true

sudo: required

script:
  - ./gradlew clean build check

cache:
  directories:
    - $HOME/.m2